name: CI_action

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Change to worksheet2 directory and install dependencies
        run: |
          cd cise_ass1a_worksheet2
          npm install

      - name: Run the tests
        run: |
          cd cise_ass1a_worksheet2
          npm test

      - name: Build
        run: |
          cd cise_ass1a_worksheet2
          npm run build
