name: CI_action

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-react:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies for React
        run: |
          cd react-project
          npm install

      - name: Run the tests for React
        run: |
          cd react-project
          npm test

      - name: Build React
        run: |
          cd react-project
          npm run build

  build-nestjs:
    runs-on: ubuntu-latest
    needs: build-react

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies for NestJS
        run: |
          cd nestjs-project
          npm install

      - name: Run the tests for NestJS
        run: |
          cd nestjs-project
          npm test

      - name: Build NestJS
        run: |
          cd nestjs-project
          npm run build
